# Generated by Django 6.0 on 2025-12-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
