# Generated by Django 6.0 on 2025-12-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attraction_image_alter_route_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routestop',
            name='duration_label',
            field=models.CharField(default='Full Day', max_length=50),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
